#%RAML 1.0 NamedExample

          [
            {  "custname": "sancho" ,
                "custaddress" : "123abc",
                "custcity" : "silverspring",
                "custstate" : "md",
                "custzipcode" : 20815,
                "delivcode" : 12345,
                "deliverydate" : 2021-11-11,
                "deliverytime" : 10:53 am ,
                "deliverymanid" : 12343,
                "unitprice" : 411.50

            }
          ]