#%RAML 1.0 NamedExample
AdminPostExample:

  {
                message: "account created successfully"
              }
      404:
        body:
       application/json:
          example:
              {
              message: "not created"
              }
      500:
        body:
          application/json:
            example:
              {
                message: "server error"
              }
