#%RAML 1.0
title: Deliveree API
description: to track and manage cust. ord. deliver asp within this api
protocols: [HTTP, HTTPS]
/delivery:
  post:
    description: creating a new customer usid/pw
    queryParameters:
      CustName:
        type: string
      Custemaile:
        type: string
        required: true
      custaddress:
        type: string
      custcity:
        type: string
      custstate: 
        type: string
      custzip:
        type: integer
      custtel: 
        type: string 
        enum: [ "home", "mobile", "office"]
    body:
      application/json:
        example:
          [
            {
            "custName": "Lucy" ,
            "custemaile": "lucy@gmail.com",
            "custaddress": "123 abc",
            "custcity" : " Bronx",
            "custstate": " New York",
            "custzip" : 12345
            }
          ]
    responses:
      201:
        body:
          application/json:
            example:
              {
                message: "account created successfully"
              }
      404:
        body:
          application/json:
            example:
              {
                message: "not created"
              }
      500:
        body:
          application/json:
            example:
              {
                message: "server error"
              }
  get:
  /{customerId}:
  




    
      

    



/customerId:




