#%RAML 1.0
title: Deliveree API
description: to track and manage cust. ord. deliver asp within this api
protocols: [HTTP, HTTPS]
/delivery:
  post:
     responses:
      201:
        body:
          application/json:
            example:
              {
                message: "account created successfully"
              }
      404:
        body:
          application/json:
            example:
              {
                message: "not created"
              }
      500:
        body:
          application/json:
            example:
              {
                message: "server error"
              }

    
  /{customerId}:
  post:
    description: create an account for deliver service
    queryParameters:
      custname:
        type: string
        description: name on the address to be delivered
        required: true
      custaddress:
        description: the address where the package will be delivered
        type: string
        required: true
        enum: [home ,work ]
      custcity:
        type: string
        required: true
      custstate:
        type: string
        required: true
      custzipcode:
        type: integer
        required: true
      delivcode:
        type: integer
        required: true
      deliverydate:
        type: date-only
        required: false
      deliverytime:
        type: datetime
        required: false
      deliverymanid:
        description: employee id number
        type: integer
        required: true
      unitprice:
        type: integer
        required: true
    body:
      application/json:
        example:
          [
            {  "custname": "sancho" ,
                "custaddress" : "123abc",
                "custcity" : "silverspring",
                "custstate" : "md",
                "custzipcode" : 20815,
                "delivcode" : 12345,
                "deliverydate" : 2021-11-11,
                "deliverytime" : 10:53 am ,
                "deliverymanid" : 12343,
                "unitprice" : 411.50

            }
          ]
    responses:
      201:
        body:
          application/json:
            example:
              {
                meg: account created successfully
              }
  get:
    description: fetch customer account
    body:
      application/json:
        example:
          {
            "custname": "sancho" ,
                "custaddress" : "123abc",
                "custcity" : "silverspring",
                "custstate" : "md",
                "custzipcode" : 20815,
                "delivcode" : 12345,
                "deliverydate" : 2021-11-11,
                "deliverytime" : 10:53 am ,
                "deliverymanid" : 12343,
                "unitprice" : 411.50

          }
    responses:
      201:
        body:
          application/json:
            example:
              {
                msg : "successfull"
              }
      404:
        body:
          application/json:
            example:
              {
                msg : unable to fetch
              }
  put:
    description: update delivery and customer account
    queryParameters:
      updatedate:
        type: date-only
        required: false
      updatetime:
        type: datetime
        required: false
      delivermanid:
        type: integer
        required: true
    body:
      application/json:
        example:
          {
            "updatedate": 2021-12-12,
            "updatetime" : 11:15am,          }



        
