#%RAML 1.0
title: Deliveree API
description: to track and manage cust. ord. deliver asp within this api
protocols: [HTTP, HTTPS]
/customers:
  post:
    description: creating a new customer usid/pw
    queryParameters:
      CustName:
        type: string
      Custemaile:
        type: string
        required: true
      custaddress:
        type: string
      custcity:
        type: string
      custstate: 
        type: string
      custzip:
        type: integer
      custtel: 
        type: string 
        enum: [ "home", "mobile", "office"]
    body:
      application/json:
        example:
          [
            {
            "custName": "Lucy" ,
            "custemaile": "lucy@gmail.com",
            "custaddress": "123 abc",
            "custcity" : " Bronx",
            "custstate": " New York"
            "custzip" : 


            }
          ]




    
      

    



/customerId:




