#%RAML 1.0 SecurityScheme
type: OAuth 2.0
description: needs token for authorization
describedBy:
  headers:
    authorization:
      description: admin needs a valid token value
      type: string
  responses:
    401:
      description: unautorized user
    403:
      description: forbidden access
  queryParameters:
    token:
      type: string
      required: true
      
    
    
    
    
    


  