#%RAML 1.0 DataType
properties:
  

    description: update delivery and customer account
  queryParameters:
   updatedate:
   type: date-only
        required: false
      updatetime:
        type: datetime
        required: false
      delivermanid:
        type: integer
        required: true