#%RAML 1.0 DataType
properties:

   updatedate:
    type:date-only
    required: false
  updatetime:
    type: datetime
      required: false
  delivermanid:
        type: integer
        required: true