#%RAML 1.0 Trait

  401:
    body:
      application/json:
        example:
          {msg: server error}

         500:
          body:
            application/json:
              example:
                {msg: server error}