#%RAML 1.0 Trait

responses:
  
  401:
    body:
      application/json:
        example:
          {msg: server error}

  404:
    body:
      application/json:
        example:
              {
                message: "not created"
              }
  401:
    body:
      application/json:
        example:
          {msg: server error}
         500:
          body:
            application/json:
              example:
                {msg: server error}